name: Lotc-Farming-Plugin-Test
version: '1.0-SNAPSHOT'
main: mc.lotcFarmingPluginTest.LotcFarmingPluginTest
api-version: '1.21'

commands:
  croptrample:
    description:
      Toggle your own ability to trample crops.
    usage: "/croptrample"
    permission: farmplugin.croptrample.default
  toggletrample:
    description:
      Toggle any player's ability to trample crops
    usage: "/croptrample <user>"
    permission: farmplugin.croptrample.admin
permissions:
  farmplugin.croptrample.default:
    description: "Enables use of the croptrample command for yourself."
    default: false
  farmplugin.croptrample.admin:
    description: "Enables use of the croptrample command for admin use."
    default: false
